"""alteracao tabela viagem

Revision ID: 523b3eced7b3
Revises: c3b4543a52b7
Create Date: 2025-12-10 10:50:51.809211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '523b3eced7b3'
down_revision: Union[str, Sequence[str], None] = 'c3b4543a52b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viagem', sa.Column('horario_chegada_api', sa.String(), nullable=False))
    op.add_column('viagem', sa.Column('data_referencia', sa.Date(), nullable=False))
    op.add_column('viagem', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('viagem', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('viagem', 'data_partida_prevista')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viagem', sa.Column('data_partida_prevista', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('viagem', 'updated_at')
    op.drop_column('viagem', 'status')
    op.drop_column('viagem', 'data_referencia')
    op.drop_column('viagem', 'horario_chegada_api')
    # ### end Alembic commands ###
