"""initial migration

Revision ID: c3b4543a52b7
Revises: 
Create Date: 2025-12-06 03:02:55.481946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3b4543a52b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('linha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('cor_hex', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('linha_estacao',
    sa.Column('id_linha', sa.Integer(), nullable=False),
    sa.Column('id_estacao', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_estacao'], ['estacao.id'], ),
    sa.ForeignKeyConstraint(['id_linha'], ['linha.id'], ),
    sa.PrimaryKeyConstraint('id_linha', 'id_estacao')
    )
    op.create_table('localizacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocorrencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('num_vagao', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('valido', sa.Boolean(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('viagem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_partida_prevista', sa.DateTime(), nullable=False),
    sa.Column('sentido', sa.String(length=50), nullable=False),
    sa.Column('id_linha', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_linha'], ['linha.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('viagem_usuario',
    sa.Column('id_viagem', sa.Integer(), nullable=False),
    sa.Column('id_estacao', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('horario_embarque', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_estacao'], ['estacao.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['id_viagem'], ['viagem.id'], ),
    sa.PrimaryKeyConstraint('id_viagem', 'id_usuario')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viagem_usuario')
    op.drop_table('viagem')
    op.drop_table('ocorrencia')
    op.drop_table('localizacao')
    op.drop_table('linha_estacao')
    op.drop_table('usuario')
    op.drop_table('linha')
    op.drop_table('estacao')
    # ### end Alembic commands ###
